### ISSUE TITLE
Where can I download the latest model weight?

### ISSUE THREAD

**Issue by dragon-cao** [AlaaLab/InstructCV#10]
Dear Authors,

I really appreciate your work. But it seems that the readme.md does not match the code in your repo? And the checkpoint link in readme.md cannot download the latest weight. Could you tell me how I can download the latest model weight?
Thanks for reading, faithful look forward to your reply!

**Comment by sunrainyg** [comment]
Hi,

Thanks for your question. You could use the code below to download model weights from Hugging Face at https://huggingface.co/alaa-lab/InstructCV:

```python
from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
model_id = "alaa-lab/InstructCV"
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(model_id, torch_dtype=torch.float16, safety_checker=None)
```

Usually you will also need to specify your use_auth_token in HF to download the weights. Let me know if you have any further questions.
