### ISSUE TITLE
Duration of Data Preprocessing

### ISSUE THREAD

**Issue by NeverBuggy** [AlaaLab/InstructCV#3]
Dear Authors,

I really appreciate your work and am exploring some related ideas. While creating the dataset, I noticed that the preprocessing phase was quite time-consuming. Could you share how long it typically takes for you to complete this step?

**Comment by sunrainyg** [comment]
Hi, Thank you for your kind words.

Creating the dataset did indeed consume a significant amount of time. I will offer you a pseudo code for your reference to expedite the process. By implementing this, it takes approximately 4 hours to generate the dataset.

```
import threading

def process_elements(start, end, input_list):
    for i in range(start, end):
        # Perform image processing operations here

my_list = list(range(1000)) # For each function responsible for generating a dataset in our code, we maintain a list to store the metadata information.

chunk_size = len(my_list) // 10 # Custom this

threads = []
for i in range(10):
    start = i * chunk_size
    end = start + chunk_size if i < 9 else len(my_list)
    thread = threading.Thread(target=process_elements, args=(start, end, my_list))
    threads.append(thread)
    thread.start()

for thread in threads:
    thread.join()
```
