### ISSUE TITLE
The processed datasets?

### ISSUE THREAD

**Issue by FanqingM** [AlaaLab/InstructCV#9]
Nice work!
I wonder if you can release the datasets after processing in your paper(InstructCV)?

**Comment by FanqingM** [comment]
python dataset_creation/format_dataset.py --save_root <path_to_save> --tasks <vision tasks> --data_root <path_to_dataset>
# specific examples
## coco
python dataset_creation/format_dataset.py --save_root './image_pairs' --tasks ['det'] --data_root './data/coco'

It seems that these codes do not match the code in your repo?
dataset_creation/format_dataset.py is not in your repo

**Comment by sunrainyg** [comment]
> Nice work! I wonder if you can release the datasets after processing in your paper(InstructCV)?

Thanks for your interest. Yes, we do consider releasing the dataset on Hugging Face for easier access. However, this may not happen soon as we are experiencing issues with accessing HF.

If you want to use it soon, you could use the codes in the build_data folder to build the dataset.

**Comment by sunrainyg** [comment]
> python dataset_creation/format_dataset.py --save_root <path_to_save> --tasks --data_root <path_to_dataset>
> 
> # specific examples
> ## coco
> python dataset_creation/format_dataset.py --save_root './image_pairs' --tasks ['det'] --data_root './data/coco'
> 
> It seems that these codes do not match the code in your repo? dataset_creation/format_dataset.py is not in your repo

I have fixed the typo; it should be build_data/format_dataset_rp/fp.py.
